#!/usr/bin/env ansible-playbook
---
- name: Undercloud part of novajoin testing
  hosts: undercloud-0
  tasks:
    - name: Copy novajoin keytab to stack user home directory
      shell: |
        cp /etc/novajoin/krb5.keytab /home/stack/krb5.keytab
        chown stack: /home/stack/krb5.keytab
      become: yes

    - name: Install gcc
      package:
        name: gcc
        state: present
      become: yes

    - name: Install gcc-c++
      package:
        name: gcc-c++
        state: present
      become: yes

    - name: Install python-devel
      package:
        name: python-devel
        state: present
      become: yes

    - name: disable strict host checking
      copy:
        dest: "/home/stack/.ssh/config"
        mode: 0400
        content: |
          Host *
              StrictHostKeyChecking no

    - name: configure REQUESTS_CA_BUNDLE variable
      lineinfile:
        dest: /etc/environment
        state: present
        regexp: '.*REQUESTS_CA_BUNDLE.*$'
        line: "export REQUESTS_CA_BUNDLE=/etc/pki/tls/certs/ca-bundle.crt"
        create: yes
      become: yes

    - name: configure REQUESTS_CA_BUNDLE variable in /etc/profile
      lineinfile:
        dest: /etc/profile
        state: present
        insertafter: EOF
        line: "export REQUESTS_CA_BUNDLE=/etc/pki/tls/certs/ca-bundle.crt"
        create: yes
      become: yes
